# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "myapp-tfstate-s3-new"
    encrypt = true
    key     = "dev/terraform.tfstate"
    region  = "ap-south-1"
  }
}
